#### Import des librairies

In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np

In [2]:
path_file = './'

ENTREPOT_PATH = '~/Bureau/utils/data/'
df = {}

In [3]:
# campagne : campagne de l'enquête PK
# starting_line : ligne de départ pour la lecture du fichier excel
# values_out_regions : lignes à exclure de la lecture du fichier excel (pour la colonne Région)
# region_column : nom de la colonne où est stockée la région


STUDIES = [
    {
        'campagne' : 2017,
        'starting_line' : 0,
        'values_out_regions' : ['Demi-intervalle de confiance'], 
        'region_column' : 'Région'
    },
    {
        'campagne' : 2021,
        'starting_line' : 1,
        'values_out_regions' : [], 
        'region_column' : ' '
    }
]

In [19]:
def load_ift_culture_ancienne_region_gcpe(campagne, start_line=1, values_out_regions=[], region_column='Région'):
    """
        Ouvre le fichier brut des informations Agreste
        et le transforme en un DataFrame pandas avec les colonnes attendues pour la suite :
        - 
        
    """

    file_name = 'ift_culture_ancienne_region_gcpe_brut_' + str(campagne)
    df['ift_culture_ancienne_region_gcpe'] = pd.read_csv(path_file+file_name+'.csv')


    # quelques retructurations sont nécessaires pour faciliter le traitement du fichier
    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].iloc[start_line:]
    df['ift_culture_ancienne_region_gcpe'].columns = df['ift_culture_ancienne_region_gcpe'].iloc[0].values
    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].iloc[1:-3]
    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].rename(columns={
        region_column : 'nom_ancienne_region'
    }).set_index('nom_ancienne_region')

    # on exclue les lignes dont la région vaut les valeurs qu'on veux exclure
    for value in values_out_regions:
        df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'][
            df['ift_culture_ancienne_region_gcpe'].index != value
        ]

    # Convertir les colonnes en float
    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].replace(
        to_replace='ns', value=np.nan
    )

    df['ift_culture_ancienne_region_gcpe']  = df['ift_culture_ancienne_region_gcpe'].applymap(
        lambda x: str(x).replace(",", ".") if pd.notna(x) else x
    )

    for col in df['ift_culture_ancienne_region_gcpe'].columns:
        df['ift_culture_ancienne_region_gcpe'][col] = pd.to_numeric(
            df['ift_culture_ancienne_region_gcpe'][col], errors='coerce'
        )

    # petite correction pour Centre val de loire.
    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].reset_index()
    df['ift_culture_ancienne_region_gcpe'].loc[
        df['ift_culture_ancienne_region_gcpe']['nom_ancienne_region'] == 'Centre' , 'nom_ancienne_region'
    ] = 'Centre-Val de Loire'

    df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].set_index('nom_ancienne_region')

    df['ift_culture_ancienne_region_gcpe'].to_csv('ift_culture_ancienne_region_gcpe_'+str(campagne)+'.csv', index=True)

In [20]:
df['ift_culture_ancienne_region_gcpe']

,Blé tendre,Blé dur,Orge,Triticale,Colza,Tournesol,Pois protéagineux,Maïs fourrage,Maïs grain,Betterave sucrière,Pomme de terre,Canne à sucre,Féverole,Soja,Lin fibre,Lin Oléagineux
nom_ancienne_region,,,,,,,,,,,,,,,,
Alsace,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aquitaine,NaN,NaN,NaN,1.9,NaN,3.1,NaN,2.2,2.8,NaN,NaN,NaN,1.1,1.7,NaN,NaN
Auvergne,3.5,NaN,NaN,2.3,5.8,2.5,NaN,2.1,3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Basse-Normandie,5.1,NaN,4.6,3.5,6.7,NaN,5.6,2.5,NaN,5.1,NaN,NaN,5.5,NaN,NaN,NaN
Bourgogne,4.3,NaN,4.9,2.4,6.9,2.5,4.0,2.3,2.9,NaN,NaN,NaN,NaN,2.1,NaN,4.0
Bretagne,4.6,NaN,4.4,3.7,3.9,NaN,NaN,2.5,2.5,NaN,17.5,NaN,3.4,NaN,NaN,NaN
Centre,5.3,5.5,4.7,2.9,6.8,3.0,5.5,2.6,3.2,6.1,12.5,NaN,3.0,NaN,NaN,5.0
Champagne-Ardenne,5.7,NaN,4.0,3.0,6.4,NaN,4.1,2.8,3.0,6.4,18.8,NaN,4.1,NaN,NaN,NaN
Franche-Comté,4.4,NaN,4.3,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.1,NaN,NaN
Guadeloupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,NaN,NaN,NaN,NaN
Haute-Normandie,6.6,NaN,5.3,NaN,6.6,NaN,5.5,2.4,NaN,5.2,17.4,NaN,4.8,NaN,5.5,NaN
Ile-de-France,6.4,NaN,4.7,NaN,6.5,NaN,5.4,NaN,2.9,5.7,13.1,NaN,4.1,NaN,NaN,NaN
La Réunion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
Languedoc-Roussillon,NaN,3.2,NaN,0.5,NaN,2.5,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Limousin,NaN,NaN,NaN,2.4,NaN,NaN,NaN,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lorraine,4.5,NaN,3.7,2.5,5.9,2.6,2.8,2.3,2.9,NaN,NaN,NaN,NaN,NaN,NaN,3.7
Martinique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
Midi-Pyrénées,3.3,4.3,2.8,2.2,5.7,2.6,4.3,2.0,2.6,NaN,NaN,NaN,1.8,1.5,NaN,2.1
Nord-Pas-de-Calais,6.3,NaN,4.7,NaN,5.1,NaN,4.7,2.5,2.3,4.7,16.5,NaN,4.7,NaN,4.5,NaN
Pays de la Loire,4.9,4.3,4.3,3.3,5.7,2.5,4.6,2.4,2.7,NaN,NaN,NaN,2.5,NaN,NaN,4.2
Picardie,5.8,NaN,4.9,NaN,6.2,NaN,5.3,2.3,2.5,5.2,16.7,NaN,4.0,NaN,4.6,NaN
Poitou-Charentes,4.9,4.8,4.5,2.8,7.5,2.6,4.6,2.3,2.9,NaN,NaN,NaN,2.4,NaN,NaN,3.5
Provence-Alpes-Côte d'Azur,NaN,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rhône-Alpes,3.2,3.0,2.8,2.0,4.5,2.7,NaN,2.4,3.0,NaN,NaN,NaN,NaN,2.1,NaN,NaN
Ensemble,5.1,4.2,4.4,2.6,6.4,2.7,4.6,2.4,2.8,5.5,16.5,2.7,3.2,1.8,5.1,3.8

In [21]:
# on applique la fonction pour obtenir le fichier final sur toutes les campagnes étudiées
for study in STUDIES :
    load_ift_culture_ancienne_region_gcpe(
        study['campagne'],
        start_line=study['starting_line'],
        values_out_regions=study['values_out_regions'], 
        region_column=study['region_column']
    )

/tmp/ipykernel_170237/1555280569.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df['ift_culture_ancienne_region_gcpe']  = df['ift_culture_ancienne_region_gcpe'].applymap(
/tmp/ipykernel_170237/1555280569.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df['ift_culture_ancienne_region_gcpe']  = df['ift_culture_ancienne_region_gcpe'].applymap(

In [12]:
df['ift_culture_ancienne_region_gcpe']

,Blé tendre,Blé dur,Orge,Triticale,Colza,Tournesol,Pois protéagineux,Maïs fourrage,Maïs grain,Betterave sucrière,Pomme de terre,Canne à sucre,Féverole,Soja,Lin fibre,Lin Oléagineux
nom_ancienne_region,,,,,,,,,,,,,,,,
Alsace,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aquitaine,NaN,NaN,NaN,1.9,NaN,3.1,NaN,2.2,2.8,NaN,NaN,NaN,1.1,1.7,NaN,NaN
Auvergne,3.5,NaN,NaN,2.3,5.8,2.5,NaN,2.1,3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Basse-Normandie,5.1,NaN,4.6,3.5,6.7,NaN,5.6,2.5,NaN,5.1,NaN,NaN,5.5,NaN,NaN,NaN
Bourgogne,4.3,NaN,4.9,2.4,6.9,2.5,4.0,2.3,2.9,NaN,NaN,NaN,NaN,2.1,NaN,4.0
Bretagne,4.6,NaN,4.4,3.7,3.9,NaN,NaN,2.5,2.5,NaN,17.5,NaN,3.4,NaN,NaN,NaN
Centre,5.3,5.5,4.7,2.9,6.8,3.0,5.5,2.6,3.2,6.1,12.5,NaN,3.0,NaN,NaN,5.0
Champagne-Ardenne,5.7,NaN,4.0,3.0,6.4,NaN,4.1,2.8,3.0,6.4,18.8,NaN,4.1,NaN,NaN,NaN
Franche-Comté,4.4,NaN,4.3,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.1,NaN,NaN
Guadeloupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,NaN,NaN,NaN,NaN
Haute-Normandie,6.6,NaN,5.3,NaN,6.6,NaN,5.5,2.4,NaN,5.2,17.4,NaN,4.8,NaN,5.5,NaN
Ile-de-France,6.4,NaN,4.7,NaN,6.5,NaN,5.4,NaN,2.9,5.7,13.1,NaN,4.1,NaN,NaN,NaN
La Réunion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
Languedoc-Roussillon,NaN,3.2,NaN,0.5,NaN,2.5,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Limousin,NaN,NaN,NaN,2.4,NaN,NaN,NaN,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lorraine,4.5,NaN,3.7,2.5,5.9,2.6,2.8,2.3,2.9,NaN,NaN,NaN,NaN,NaN,NaN,3.7
Martinique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
Midi-Pyrénées,3.3,4.3,2.8,2.2,5.7,2.6,4.3,2.0,2.6,NaN,NaN,NaN,1.8,1.5,NaN,2.1
Nord-Pas-de-Calais,6.3,NaN,4.7,NaN,5.1,NaN,4.7,2.5,2.3,4.7,16.5,NaN,4.7,NaN,4.5,NaN
Pays de la Loire,4.9,4.3,4.3,3.3,5.7,2.5,4.6,2.4,2.7,NaN,NaN,NaN,2.5,NaN,NaN,4.2
Picardie,5.8,NaN,4.9,NaN,6.2,NaN,5.3,2.3,2.5,5.2,16.7,NaN,4.0,NaN,4.6,NaN
Poitou-Charentes,4.9,4.8,4.5,2.8,7.5,2.6,4.6,2.3,2.9,NaN,NaN,NaN,2.4,NaN,NaN,3.5
Provence-Alpes-Côte d'Azur,NaN,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rhône-Alpes,3.2,3.0,2.8,2.0,4.5,2.7,NaN,2.4,3.0,NaN,NaN,NaN,NaN,2.1,NaN,NaN
Ensemble,5.1,4.2,4.4,2.6,6.4,2.7,4.6,2.4,2.8,5.5,16.5,2.7,3.2,1.8,5.1,3.8