In [1]:
import pandas as pd
import numpy as np

In [2]:
ENTREPOT_PATH = '/home/tbadie/Bureau/data/data_entrepot_outils/'
EXTERNAL_DATA_PATH = '/home/tbadie/Bureau/data/temp/typologie_dirodur/'
donnees = {}

def import_dfs(df_names, path_data, sep = ','):
    i = 0
    for df_name in df_names: 
        donnees[df_name] = pd.read_csv(path_data+df_name+'.csv', sep = sep, low_memory=False).replace({'\r\n': '\n'}, regex=True)

tables = [
    'composant_culture', 
    'culture',
    # 'espece',
    'connection_synthetise',
    'noeuds_synthetise_restructure',
    'noeuds_realise',
    'entite_unique_par_sdc_nettoyage', 
    'noeuds_synthetise',
    'synthetise',
    'zone',
    'parcelle',
    'sdc',
    'date_de_semis_outils_dirodur',
    'typologie_can_culture'
]

tables_ext = [
    'espece',
    'matrice_typologie_culture_dirodur'
]

# import des données
import_dfs(tables, ENTREPOT_PATH, sep = ',')
import_dfs(tables_ext, EXTERNAL_DATA_PATH, sep = ',')

In [3]:
list_culture_choisies = [
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_0e9ada58-c35a-4fba-bddb-df75de74cecf',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_140e02c4-4a90-4c88-9694-f3e644e1689e',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_1df98e48-d62e-4902-8c2a-67133c15c00a',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_2f961859-00ee-44f2-a11a-747845d05189',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_2fb18a07-d5a5-4b36-b453-03ff31fc36f0',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_3478eb36-740a-40b5-96fa-28d29d931605',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_375e215e-d98c-4245-bdc9-47519239fe50',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_508f5758-cca8-4ce7-beed-bd40751282bd',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_51bae500-cf3f-401d-a7f6-471009e79423',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_57b4733c-ad1d-4502-a1fc-70068207d81b',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_9dcc5df9-a496-4918-96a4-7306d3dafc26',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_9f5d9cef-a655-4a2a-b7a1-171457732756',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_a99f84db-19fe-455d-8549-aef979bbec4b',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_af889624-cb5b-4277-a068-e8e04ccd4795',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_b2409321-a504-4a70-b895-3f13b01fed4d',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_b4967e40-d2f4-4e9b-82dd-63f360e9ccd7',
    'fr.inra.agrosyst.api.entities.CroppingPlanEntry_bc1478a1-cfb1-481f-a76b-7bfdf77746bf'
    ]

In [4]:
composant_culture = donnees['composant_culture'].copy()
composant_culture = composant_culture.loc[composant_culture['culture_id'].isin(list_culture_choisies)]

culture = donnees['culture'].copy()
culture = culture.loc[culture['id'].isin(list_culture_choisies)]

date_de_semis_outils_dirodur = donnees['date_de_semis_outils_dirodur'].copy()
date_de_semis_outils_dirodur = date_de_semis_outils_dirodur.loc[date_de_semis_outils_dirodur['culture_id'].isin(list_culture_choisies)]

typologie_can_culture = donnees['typologie_can_culture'].copy()
typologie_can_culture = typologie_can_culture.loc[typologie_can_culture['culture_id'].isin(list_culture_choisies)]

noeuds_realise = donnees['noeuds_realise'].copy()
noeuds_realise = noeuds_realise.loc[noeuds_realise['culture_id'].isin(list_culture_choisies)]

noeuds_synthetise_restructure = donnees['noeuds_synthetise_restructure'].copy()
noeuds_synthetise_restructure = noeuds_synthetise_restructure.loc[noeuds_synthetise_restructure['culture_id'].isin(list_culture_choisies)]

noeuds_synthetise = donnees['noeuds_synthetise'].copy()
noeuds_synthetise = noeuds_synthetise.loc[noeuds_synthetise['id'].isin(noeuds_synthetise_restructure['id'])]

connection_synthetise = donnees['connection_synthetise'].copy()
connection_synthetise = connection_synthetise.loc[connection_synthetise['cible_noeuds_synthetise_id'].isin(noeuds_synthetise_restructure['id'])]

zone = donnees['zone'].copy()
zone = zone.loc[zone['id'].isin(noeuds_realise['zone_id'])]

parcelle = donnees['parcelle'].copy()
parcelle = parcelle.loc[parcelle['id'].isin(zone['parcelle_id'])]

synthetise = donnees['synthetise'].copy()
synthetise = synthetise.loc[synthetise['id'].isin(noeuds_synthetise['synthetise_id'])]

sdc = donnees['sdc'].copy()
sdc = sdc.loc[sdc['id'].isin(synthetise['sdc_id']) | (sdc['id'].isin(parcelle['sdc_id']))]

entite_unique_par_sdc_nettoyage = donnees['entite_unique_par_sdc_nettoyage'].copy()
entite_unique_par_sdc_nettoyage = entite_unique_par_sdc_nettoyage.loc[entite_unique_par_sdc_nettoyage['sdc_id'].isin(sdc['id'])]

In [5]:
PATH_TEST='/home/tbadie/Bureau/catalogue_script_agrosyst/02_outils/tests/data/test_get_typologie_culture_dirodur/'

noeuds_realise.to_csv(PATH_TEST+'noeuds_realise.csv', index=False)
noeuds_synthetise.to_csv(PATH_TEST+'noeuds_synthetise.csv', index=False)
noeuds_synthetise_restructure.to_csv(PATH_TEST+'noeuds_synthetise_restructure.csv', index=False)
connection_synthetise.to_csv(PATH_TEST+'connection_synthetise.csv', index=False)
zone.to_csv(PATH_TEST+'zone.csv', index=False)
parcelle.to_csv(PATH_TEST+'parcelle.csv', index=False)
synthetise.to_csv(PATH_TEST+'synthetise.csv', index=False)
sdc.to_csv(PATH_TEST+'sdc.csv', index=False)

entite_unique_par_sdc_nettoyage.to_csv(PATH_TEST+'entite_unique_par_sdc_nettoyage.csv', index=False)
composant_culture.to_csv(PATH_TEST+'composant_culture.csv', index=False)
culture.to_csv(PATH_TEST+'culture.csv', index=False)
date_de_semis_outils_dirodur.to_csv(PATH_TEST+'date_de_semis_outils_dirodur.csv', index=False)
typologie_can_culture.to_csv(PATH_TEST+'typologie_can_culture.csv', index=False)

donnees['espece'].to_csv(PATH_TEST+'espece.csv', index=False)
donnees['matrice_typologie_culture_dirodur'].to_csv(PATH_TEST+'matrice_typologie_culture_dirodur.csv', index=False)

In [8]:
tables = [
    'composant_culture', 
    'culture',
    'connection_synthetise',
    'noeuds_synthetise_restructure',
    'noeuds_realise',
    'entite_unique_par_sdc_nettoyage', 
    'noeuds_synthetise',
    'synthetise',
    'zone',
    'parcelle',
    'sdc',
    'date_de_semis_outils_dirodur',
    'typologie_can_culture',

    'espece',
    'matrice_typologie_culture_dirodur'
]

In [9]:
del donnees
donnees = {}
import_dfs(tables, PATH_TEST, sep = ',')

In [10]:
sp = donnees['espece'][['id','typodirodur_espece','typodirodur_espece_precise','typodirodur_espece_famille_bota','typodirodur_espece_periode_semis']].rename(columns={'id':'espece_id'}).copy()
matrice = donnees['matrice_typologie_culture_dirodur'][['typodirodur_espece','typodirodur_culture', 'culture_est_avec_compagne', 
                                                        'culture_est_annuelle_asso', 'culture_est_prairie', 'besoin_saison']].copy()

# sp = donnees['espece'][['id','typodirodur_espece','typodirodur_espece_precise','typodirodur_espece_famille_bota','typodirodur_espece_periode_semis']].rename(columns={'id':'espece_id'}).copy()
# matrice = donnees['matrice_dirodur_passage_espece_culture'][['typodirodur_espece', 'typodirodur_culture', 'culture_est_avec_compagne', 'culture_est_annuelle_asso', 'culture_est_prairie', 'culture_principale', 'besoin_saison']].copy()

cropsp = donnees['composant_culture'][['id','espece_id','culture_id','compagne']].rename(columns={'id':'composant_culture_id'}).copy()
crop = donnees['culture'][['id','nom','type']].rename(columns={'id':'culture_id'}).copy()
date_semis = donnees['date_de_semis_outils_dirodur'][['culture_id','saison_semis_detect_via_intv']].copy()
typocan = donnees['typologie_can_culture'][['culture_id','typo_cpg']].copy()

df = cropsp.merge(sp, how = 'left', on = 'espece_id')

df['nb_composant_culture'] = 1
df['nb_typodirodur_espece'] = df['typodirodur_espece'].copy()
df['nb_typodirodur_espece_precise'] = df['typodirodur_espece_precise'].copy()
df['nb_typodirodur_espece_famille_bota'] = df['typodirodur_espece_famille_bota'].copy()

def concat_unique_sorted(series):
    cleaned = series.dropna().unique()
    if len(cleaned) == 0:
        return np.nan
    return '_'.join(sorted(cleaned))

def get_nb_unique_typo(series):
    cleaned = series.dropna().unique()
    return len(cleaned)

agg_dict = {
    'nb_composant_culture': 'sum',
    'typodirodur_espece': concat_unique_sorted,
    'typodirodur_espece_precise': concat_unique_sorted,
    'typodirodur_espece_famille_bota': concat_unique_sorted,
    'typodirodur_espece_periode_semis': concat_unique_sorted,
    'nb_typodirodur_espece': get_nb_unique_typo,
    'nb_typodirodur_espece_precise': get_nb_unique_typo,
    'nb_typodirodur_espece_famille_bota': get_nb_unique_typo,
}

#  On crée les typologie can culture et les autre variable utiles grace a agg_dict
df = df[['culture_id',
        'nb_composant_culture',
        'typodirodur_espece',
        'typodirodur_espece_precise',
        'typodirodur_espece_famille_bota',
        'typodirodur_espece_periode_semis',
        'nb_typodirodur_espece',
        'nb_typodirodur_espece_precise',
        'nb_typodirodur_espece_famille_bota']].groupby('culture_id').agg(agg_dict).reset_index()

# On ajoute les type des culture_id
# On fait un outer pour avoir toutes les cultures meme celles qui n'ont pas de composant_culture
df = df.merge(crop[['culture_id','nom','type']], how='outer', on='culture_id')

df.loc[df['nb_composant_culture'].isna(),['nb_composant_culture','nb_typodirodur_espece','nb_typodirodur_espece_precise','nb_typodirodur_espece_famille_bota']] = 0

# Les culture dont la colonne besoin_saison est vide sont les cultures dont la saion ne défnini pas la typologie de culture.
# 1. On récupère les date de semis réel (vu via l'intervention) au cas où nous avons besoin de la saison et qu'elle ne soit pas dispo dans le referentiel espece
df = df.merge(date_semis, how='left', on='culture_id')
df['typodirodur_espece_periode_semis'] = df['typodirodur_espece_periode_semis'].fillna(df['saison_semis_detect_via_intv'])
df.drop(columns='saison_semis_detect_via_intv', inplace=True)

In [11]:
df

,culture_id,nb_composant_culture,typodirodur_espece,typodirodur_espece_precise,typodirodur_espece_famille_bota,typodirodur_espece_periode_semis,nb_typodirodur_espece,nb_typodirodur_espece_precise,nb_typodirodur_espece_famille_bota,nom,type
0,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Betterave,Betterave Sucrière,Amaranthaceae,printemps,1,1,1,Betterave,MAIN
1,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Oignon,Ail,Amaryllidaceae,printemps,1,1,1,Ail rose pcdt Blé t (JARDIROSE),MAIN
2,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Prairie,Prairie permanente fauchée,NaN,pluriannuelle,1,1,0,Prairie permanante,MAIN
3,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Mais,Maïs,Poaceae,ete,1,1,1,MAIS ENSILAGE,MAIN
4,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Sorgho,Sorgho Grain(es),Poaceae,ete,1,1,1,SORGHO,MAIN
5,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,3,Avoine_Pois_Triticale,Avoine Blanche Hiver_Pois Fourrager / Fourrage...,Fabaceae_Poaceae,hiver,3,3,2,Méteil dérobé,CATCH
6,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Oléagineux Hiver_Pois Protéagineux Print...,Brassicaceae_Fabaceae,automne_printemps,2,2,2,couvert,INTERMEDIATE
7,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Ble tendre,Blé tendre Hiver Meunier,Poaceae,hiver,1,1,1,BLE TENDRE D'HIVER,MAIN
8,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Fourrager / Fourrage Hiver_Pois Protéagi...,Brassicaceae_Fabaceae,automne_hiver,2,2,2,Pois hiver,MAIN
9,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Prairie,Mélange enherbement non fourrager,NaN,NaN,1,1,0,Mélange,MAIN
10,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Triticale,Triticale,Poaceae,hiver,1,1,1,Triticale,MAIN
11,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,3,Ray grass_Trefle,Ray-grass d'Italie_Trèfle violet,Fabaceae_Poaceae,pluriannuelle,2,2,2,Ray grass - Treffle,MAIN
12,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Ble tendre,Blé tendre Hiver Biscuit,Poaceae,hiver,1,1,1,Blé tendre,MAIN
13,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,4,Mais,Maïs,Poaceae,ete,1,1,1,Maïs,MAIN
14,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Trefle,Trèfle violet,Fabaceae,pluriannuelle,1,1,1,TREFLE VIOLET,MAIN
15,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Fourrager / Fourrage Hiver_Pois Protéagi...,Brassicaceae_Fabaceae,automne_hiver,2,2,2,Pois hiver,MAIN
16,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Ray grass_Trefle,Ray-grass hybride_Trèfle violet,Fabaceae_Poaceae,pluriannuelle,2,2,2,Prairie temporaire RGH+TV,MAIN

In [12]:
# 2. On regarde les cultures qui ont un besoin de saison pour faire le merge avec la matrice
# Pour le savoir on regarde si la matrice a une valeur non nulle dans la colonne typodirodur_espece_periode_semis. Si c'est le cas, on merge avec la matrice pour récupérer le typodirodur_culture correspondant.
# Dans le cas ou l'on a besoin de savoir la saison mais que la saison n'est pas renseigné dans le referentiel espece, on prend la saison détecté via les interventions.
matrice_saison_needed = matrice.loc[matrice['besoin_saison'].notna()]
typo_espece_en_pluriannuelle = matrice_saison_needed.loc[matrice_saison_needed['besoin_saison'] == 'pluriannuelle', 'typodirodur_espece'].to_list()

df_saison_needed = df.copy()
df_saison_needed['typodirodur_espece_periode_semis'] = np.where(
    (df_saison_needed['typodirodur_espece'].isin(typo_espece_en_pluriannuelle)) & (df_saison_needed['typodirodur_espece_periode_semis'].str.contains('pluriannuelle')),
    'pluriannuelle', 
    df_saison_needed['typodirodur_espece_periode_semis'])
matrice_saison_needed.rename(columns={'besoin_saison' : 'typodirodur_espece_periode_semis'}, inplace=True)
df_saison_needed = df_saison_needed.merge(matrice_saison_needed, how='inner', on=['typodirodur_espece', 'typodirodur_espece_periode_semis'])
df_saison_needed = df_saison_needed.loc[df_saison_needed['typodirodur_culture'].notna()]

/tmp/ipykernel_207320/3852994318.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matrice_saison_needed.rename(columns={'besoin_saison' : 'typodirodur_espece_periode_semis'}, inplace=True)

In [13]:

# 3. On regarde les cultures qui n'ont pas de besoin de saison pour faire le merge avec la matrice
# Ce sont donc les culture_id qui ne sont pas dans df_saison_needed. On les merge avec la matrice pour récupérer le typodirodur_culture correspondant.
df_no_saison_needed = df.copy()
df_no_saison_needed = df_no_saison_needed.loc[~df_no_saison_needed['culture_id'].isin(df_saison_needed['culture_id'])]
df_no_saison_needed = df_no_saison_needed.merge(matrice.loc[matrice['besoin_saison'].isna()], how='left', on=['typodirodur_espece'])
df_no_saison_needed = df_no_saison_needed.loc[df_no_saison_needed['typodirodur_culture'].notna()]

# 4. On concat les deux df pour avoir le df final
df = pd.concat([df_no_saison_needed, df_saison_needed], ignore_index=True)

# On ajoute les culture porte-graines
df = df.merge(typocan, how='left', on='culture_id')

df['type'] = df['type'].astype('category')
    
df['type'] = df['type'].cat.rename_categories({'MAIN': 'principale', 
                                                'INTERMEDIATE': 'intermediaire', 
                                                'CATCH': 'derobee' })
df['type'] = df['type'].astype('str')

df[['nb_typodirodur_espece','nb_composant_culture','nb_typodirodur_espece_precise','nb_typodirodur_espece_famille_bota']] = df[['nb_typodirodur_espece','nb_composant_culture','nb_typodirodur_espece_precise','nb_typodirodur_espece_famille_bota']].astype('int64')

In [15]:
df

,culture_id,nb_composant_culture,typodirodur_espece,typodirodur_espece_precise,typodirodur_espece_famille_bota,typodirodur_espece_periode_semis,nb_typodirodur_espece,nb_typodirodur_espece_precise,nb_typodirodur_espece_famille_bota,nom,type,typodirodur_culture,culture_est_avec_compagne,culture_est_annuelle_asso,culture_est_prairie,besoin_saison,typo_cpg
0,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Betterave,Betterave Sucrière,Amaranthaceae,printemps,1,1,1,Betterave,principale,Betterave,non,non,non,NaN,NaN
1,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Oignon,Ail,Amaryllidaceae,printemps,1,1,1,Ail rose pcdt Blé t (JARDIROSE),principale,Oignon,non,non,non,NaN,NaN
2,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Prairie,Prairie permanente fauchée,NaN,pluriannuelle,1,1,0,Prairie permanante,principale,PT,non,non,oui,NaN,NaN
3,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Mais,Maïs,Poaceae,ete,1,1,1,MAIS ENSILAGE,principale,Mais,non,non,non,NaN,NaN
4,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Sorgho,Sorgho Grain(es),Poaceae,ete,1,1,1,SORGHO,principale,Sorgho,non,non,non,NaN,NaN
5,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,3,Avoine_Pois_Triticale,Avoine Blanche Hiver_Pois Fourrager / Fourrage...,Fabaceae_Poaceae,hiver,3,3,2,Méteil dérobé,derobee,asso_cer_leg,non,oui,non,NaN,NaN
6,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Ble tendre,Blé tendre Hiver Meunier,Poaceae,hiver,1,1,1,BLE TENDRE D'HIVER,principale,Ble tendre,non,non,non,NaN,NaN
7,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Prairie,Mélange enherbement non fourrager,NaN,NaN,1,1,0,Mélange,principale,PT,non,non,oui,NaN,NaN
8,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Triticale,Triticale,Poaceae,hiver,1,1,1,Triticale,principale,Triticale,non,non,non,NaN,NaN
9,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Ble tendre,Blé tendre Hiver Biscuit,Poaceae,hiver,1,1,1,Blé tendre,principale,Ble tendre,non,non,non,NaN,NaN
10,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,4,Mais,Maïs,Poaceae,ete,1,1,1,Maïs,principale,Mais,non,non,non,NaN,Cultures porte graines
11,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Oléagineux Hiver_Pois Protéagineux Print...,Brassicaceae_Fabaceae,automne_printemps,2,2,2,couvert,intermediaire,Colza,oui,oui,non,NaN,NaN
12,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Fourrager / Fourrage Hiver_Pois Protéagi...,Brassicaceae_Fabaceae,automne_hiver,2,2,2,Pois hiver,principale,asso_cruc_leg,non,oui,non,NaN,NaN
13,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,3,Ray grass_Trefle,Ray-grass d'Italie_Trèfle violet,Fabaceae_Poaceae,pluriannuelle,2,2,2,Ray grass - Treffle,principale,PT_cer_leg,non,non,oui,NaN,NaN
14,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,1,Trefle,Trèfle violet,Fabaceae,pluriannuelle,1,1,1,TREFLE VIOLET,principale,PT_trefle,non,non,oui,NaN,NaN
15,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Colza_Pois,Colza Fourrager / Fourrage Hiver_Pois Protéagi...,Brassicaceae_Fabaceae,automne_hiver,2,2,2,Pois hiver,principale,asso_cruc_leg,non,oui,non,NaN,NaN
16,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,2,Ray grass_Trefle,Ray-grass hybride_Trèfle violet,Fabaceae_Poaceae,pluriannuelle,2,2,2,Prairie temporaire RGH+TV,principale,PT_cer_leg,non,non,oui,NaN,NaN